### ISSUE TITLE
Default consent wait_for_update cannot be 0

### ISSUE THREAD

**Issue by lanzone1** [netgohu/tagmanager_consent_template#1]
When reviewing your template we've noticed that the `setDefaultConsentState` call does not always include the [wait_for_update](https://developers.google.com/tag-platform/tag-manager/templates/api#setdefaultconsentstate) option. If the users set it to 0, this option is skipped. A non-zero value is required for any asynchronous consent management script load to delay tag execution.

**Comment by netgohu** [comment]
It's modified. It can be zero.

**Comment by lanzone1** [comment]
Thanks for the update. Two notes:
1. Users are still able to set `wait_for_update` to 0. To prevent that, you can change the validation logic on `wait_for_update` to
```javascript
"valueValidators": ["POSITIVE_NUMBER"],
```
2. Please update the `sha` value in metadata.yaml to match the latest version.

**Comment by netgohu** [comment]
Thanks for your notes.
wait_for_update  valueValidators is set to POSITIVE_NUMBER
metadata.yaml is updated

**Comment by lanzone1** [comment]
Thanks for making the change. One last problem: the order of commits in metadata.yaml is backwards. The latest version [should be at the top](https://developers.google.com/tag-platform/tag-manager/templates/gallery#update_your_template).

**Comment by netgohu** [comment]
The order of commits in metadata.yaml is changed.
